# Generated by Django 5.2.4 on 2025-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_order', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('lead_html', models.TextField()),
                ('detail_html', models.TextField()),
                ('hint_text', models.CharField(default='Tap me to unlock the fish!', max_length=120)),
                ('read_seconds', models.PositiveSmallIntegerField(default=4)),
                ('is_starter', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kids_card',
                'ordering': ['card_order'],
                'managed': False,
            },
        ),
    ]
